#!/bin/bash
#SBATCH --account=ucb543_asc2
#SBATCH --qos=long
#SBATCH --partition=amilan
#SBATCH --nodes=1
#SBATCH --ntasks=48
#SBATCH --time=1-00:00:00
#SBATCH --job-name=ROMS_run_beaufort_double_dis
#SBATCH --output=beaufort_rivers_10rivs_13seabed_dbsed0001_double_dis_rst.%j.out
##SBATCH --constraint=ib

#sinteractive

pwd
echo "Initial Module List"
module list
module purge
module load intel/2022.1.2
module load impi
module load netcdf
echo "Final Module List"
module list

echo "NETCDF PATH"
which nc-config

echo "MPI Path"
which mpirun

echo "Run ROMS"
echo "Need to test syntax"
export I_MPI_FABRICS=shm
mpirun -np $SLURM_NTASKS ./coawstM /projects/brun1463/ROMS/Beaufort_Shelf_Rivers_Alpine_002/Beaufort_AK_002/ocean_beaufort_ak_002_double_dis.in 

echo "==End of Job=="
EOF
