#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=20
#SBATCH --time=12:00:00
#SBATCH --qos=normal
#SBATCH --partition=amilan
#SBATCH --job-name=ssc_comp_time
#SBATCH --output=ssc_comp_time_006.out

module purge
module load anaconda
conda activate xesmf_env

python3 plot_ssc_composition_in_sections_barcharts_over_time.py
