#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=25
#SBATCH --time=10:00:00
#SBATCH --qos=mem
#SBATCH --partition=amem
#SBATCH --mem=400G
#SBATCH --job-name=plot_percent_ssc_rivs_seabed
#SBATCH --output=plot_percent_ssc_rivs_seabed_001.out

module purge
module load anaconda
conda activate xroms

python3 plot_percent_ssc_rivs_seabed.py
