#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=25
#SBATCH --time=03:00:00
#SBATCH --qos=mem
#SBATCH --partition=amem
#SBATCH --mem=400G
#SBATCH --job-name=percent_time_ssc_above_value
#SBATCH --output=percent_time_ssc_above_value_001.out

module purge
module load anaconda
conda activate xroms

python3 plot_percent_time_ssc_above_value.py
